version: 3
vars:
  ts_suffix:
    sh: tailscale dns status | awk '/suffix =/ {gsub(")","");print $NF}'
tasks:
##
## Bootstrap
##
  intermediate-fullchain:
    desc: Deploy the PKI and creates the root CA
    cmd: bash ./scripts/deploy-pki.sh
    generates: [dist/intermediate-fullchain.pem]

  bootstrap:
    desc: Deploy the bootstrap instance
    deps: [intermediate-fullchain]
    cmd: bash ./scripts/deploy-bootstrap.sh

  forge:
    desc: Deploy the forge instance
    cmd: bash ./scripts/deploy-forge.sh

##
## Platform
##
  management:
    desc: Deploy the management instance
    prompt:
    - You should read https://tailscale.com/kb/1236/kubernetes-operator. Is it OK?
    cmd: RING0_ROOT=$PWD bash ./scripts/deploy-management.sh

  idp:
    desc: Deploy the IDP using Helm
    prompt: You should have a look at https://idp.{{.ts_suffix}}/if/flow/initial-setup/ for post-deployment configuration. Right?
    cmd: bash ./scripts/deploy-idp.sh

  cmdb:
    desc: Deploy the CMDB using Helm
    cmd: bash ./scripts/deploy-cmdb.sh

  bmaas:
    desc: Deploy the BMaaS and the OCI registry using helm
    cmd: bash ./scripts/deploy-bmaas.sh

##
## Dangerous tasks
##
  destroy-management:
    desc: Destroy the management instance
    prompt:
      - This is a dangerous command... Do you want to continue?
      - Are you sure?
    cmds:
      - if incus list | grep -q management ; then incus delete -f management ; else echo management instance already deleted ; fi
      - rm -f dist/controlplane.yaml dist/worker.yaml dist/talosconfig dist/cp-patch.yaml dist/patch.yaml dist/authentik-values.yaml
      - kubectl config delete-context admin@management

  dist-clean:
    desc: Removes the distribution artifacts
    prompt:
      - This is a dangerous command... Do you want to continue?
      - Are you sure?
    dir: '{{.USER_WORKING_DIR}}/dist'
    cmd: rm -rf *
