version: 3
vars:
  ts_suffix:
    sh: tailscale dns status | awk '/suffix =/ {gsub(")","");print $NF}'
tasks:
##
## Bootstrap
##
  intermediate-fullchain:
    desc: Deploy the PKI and creates the root CA
    cmd: bash ./scripts/deploy-pki.sh
    generates: [dist/intermediate-fullchain.pem]

  bootstrap:
    desc: Deploy the bootstrap instance
    deps: [intermediate-fullchain]
    cmd: bash ./scripts/deploy-bootstrap.sh

  forge:
    desc: Deploy the forge instance
    cmd: bash ./scripts/deploy-forge.sh

##
## Platform
##
  management:
    desc: Deploy the management instance
    prompt:
    - You should read https://tailscale.com/kb/1236/kubernetes-operator. Is it OK?
    cmd: RING0_ROOT=$PWD bash ./scripts/deploy-management.sh

  idp:
    desc: Deploy the IDP using Helm
    prompt: You should have a look at https://idp.{{.ts_suffix}}/if/flow/initial-setup/ for post-deployment configuration. Right?
    cmd: bash ./scripts/deploy-idp.sh

  cmdb:
    desc: Deploy the CMDB using Helm
    cmd: bash ./scripts/deploy-cmdb.sh

  bmaas:
    desc: Deploy the BMaaS and the OCI registry using helm
    cmd: bash ./scripts/deploy-bmaas.sh

##
## Dangerous tasks
##
  destroy-management:
    desc: Destroy the management instance
    prompt:
      - This is a dangerous command... Do you want to continue?
      - Are you sure?
    cmds:
      - if incus list | grep -q management ; then incus delete -f management ; else echo management instance already deleted ; fi
      - rm -f dist/controlplane.yaml dist/worker.yaml dist/talosconfig dist/cp-patch.yaml dist/patch.yaml dist/authentik-values.yaml
      - kubectl config delete-context admin@management

  dist-clean:
    desc: Removes the distribution artifacts
    prompt:
      - This is a dangerous command... Do you want to continue?
      - Are you sure?
    dir: '{{.USER_WORKING_DIR}}/dist'
    cmd: rm -rf *

##
## Day 2 operations
##
  update-kamaji:
    desc: Update Kamaji CRDs and manifests from the official repository and apply to the cluster
    vars:
      manifests_dir: ./core-services/management/manifests/05-kamaji
      kamaji_dir: ./dist/kamaji
      helm_set: >-
        --namespace kamaji-system
        --set defaultDatastoreName=microcloud
        --set "kamaji-etcd.deploy=false"
        --set serviceMonitor.enabled=false
      sed:
        sh: if [[ "$(uname)" == "Darwin" ]]; then echo gsed; else echo sed; fi 
    cmds:
      - |
        if [ ! -d {{.kamaji_dir}}/.git ]; then
          git clone https://github.com/clastix/kamaji.git {{.kamaji_dir}}
        fi
      - git -C {{.kamaji_dir}} fetch --tags
      - git -C {{.kamaji_dir}} checkout $(git -C {{.kamaji_dir}} tag | grep edge | tail -n1)
      - helm dependency build {{.kamaji_dir}}/charts/kamaji
      - helm template kamaji-crds {{.kamaji_dir}}/charts/kamaji-crds | yq > {{.manifests_dir}}/crds.yaml
      - |
        helm template kamaji {{.kamaji_dir}}/charts/kamaji {{.helm_set}} \
          --show-only templates/rbac.yaml \
          | grep -v "^# Source:" | yq > {{.manifests_dir}}/rbacs.yaml
      - |
        { helm template kamaji {{.kamaji_dir}}/charts/kamaji {{.helm_set}} \
            --show-only templates/service_metrics.yaml
          helm template kamaji {{.kamaji_dir}}/charts/kamaji {{.helm_set}} \
            --show-only templates/service_webhook.yaml
        } | grep -v "^# Source:" | yq > {{.manifests_dir}}/services.yaml
      - |
        { helm template kamaji {{.kamaji_dir}}/charts/kamaji {{.helm_set}} \
            --show-only templates/certmanager_issuer.yaml
          helm template kamaji {{.kamaji_dir}}/charts/kamaji {{.helm_set}} \
            --show-only templates/certmanager_certificate.yaml
        } | grep -v "^# Source:" | yq > {{.manifests_dir}}/certificate.yaml
      - |
        { helm template kamaji {{.kamaji_dir}}/charts/kamaji {{.helm_set}} \
            --show-only templates/mutatingwebhookconfiguration.yaml
          helm template kamaji {{.kamaji_dir}}/charts/kamaji {{.helm_set}} \
            --show-only templates/validatingwebhookconfiguration.yaml
        } | grep -v "^# Source:" | yq > {{.manifests_dir}}/webhook-configs.yaml
      - |
          KAMAJI_VERSION=$(git -C {{.kamaji_dir}} tag | grep edge | tail -n1)
          {{.sed}} -i -E "s,image: .+,image: \"clastix/kamaji:$KAMAJI_VERSION\"," {{.manifests_dir}}/deployment.yaml

      - kubectl apply --server-side --force-conflicts -f {{.manifests_dir}}/crds.yaml
      - kubectl apply -f {{.manifests_dir}}/namespace.yaml
      - kubectl apply -f {{.manifests_dir}}/rbacs.yaml
      - kubectl apply -f {{.manifests_dir}}/services.yaml
      - kubectl apply -f {{.manifests_dir}}/certificate.yaml
      - kubectl apply -f {{.manifests_dir}}/webhook-configs.yaml
      - kubectl apply -f {{.manifests_dir}}/deployment.yaml

  update-flatcar-repo:
    desc: Download the latest version of Flatcar Linux artifacts and set the current symlink
    cmd: cat ./core-services/bootstrap/update-flatcar-repo.sh | incus exec bootstrap bash --