apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-cilium.yaml
  - helm-jetstack.yaml
  - helm-cnpg.yaml
  - helm-tailscale.yaml
  - helm-external-secrets.yaml
  - helm-authentik.yaml
  - helm-zot.yaml
  - helm-clastix.yaml
  - oci-netbox.yaml
  - oci-tinkerbell.yaml
