version: 3
vars:
  skopeo_opts: --dest-tls-verify=false --override-arch=amd64 --override-os=linux
  ts_suffix:
    sh: tailscale dns status | awk '/suffix =/ {gsub(")","");print $NF}'
tasks:
  #############################################################################
  # butane
  #
  create-butane-oci:
    desc: Create the butane tinkerbell action OCI image
    vars:
      image_build_commands: nix-build /var/build/butane.nix ; cat result > /var/build/butane.tar.gz
      image_name: butane
    cmds:
      - mkdir -p dist
      - incus file push butane.nix forge/root/
      - incus exec forge -- apt install -y skopeo
      - incus exec forge -- docker pull nixos/nix
      - incus exec forge -- docker run --privileged --volume /root:/var/build nixos/nix bash -c "{{.image_build_commands}}"
      - incus file pull forge/root/butane.tar.gz dist/
    generates:
      - dist/{{.image_name}}.tar.gz
    status:
      - test -f dist/{{.image_name}}.tar.gz
    sources:
      - "{{.image_name}}.nix"
  push-butane-oci:
    desc: Push butane OCI to the registry
    preconditions:
      - test -f dist/{{.image_name}}.tar.gz
    vars:
      image_name: butane
    sources:
      - "{{.image_name}}.nix"
    cmds:
      - skopeo copy {{.skopeo_opts}} docker-archive:dist/{{.image_name}}.tar.gz docker://registry.{{.ts_suffix}}:443/{{.image_name}}:latest
  #############################################################################
  # flatcar-install
  #
  create-flatcar-install-oci:
    desc: Create the flatcar-install tinkerbell action OCI image
    vars:
      image_build_commands: nix-build /var/build/flatcar-install.nix ; cat result > /var/build/flatcar-install.tar.gz
      image_name: flatcar-install
    cmds:
      - mkdir -p dist
      - incus file push flatcar-install.nix forge/root/
      - incus exec forge -- apt install -y skopeo
      - incus exec forge -- docker pull nixos/nix
      - incus exec forge -- docker run --privileged --volume /root:/var/build nixos/nix bash -c "{{.image_build_commands}}"
      - incus file pull forge/root/flatcar-install.tar.gz dist/
    generates:
      - dist/{{.image_name}}.tar.gz
    status:
      - test -f dist/{{.image_name}}.tar.gz
    sources:
      - "{{.image_name}}.nix"
  push-flatcar-install-oci:
    desc: Push flatcar-install OCI to the registry
    preconditions:
      - test -f dist/{{.image_name}}.tar.gz
    vars:
      image_name: flatcar-install
    cmds:
      - skopeo copy {{.skopeo_opts}} docker-archive:dist/{{.image_name}}.tar.gz docker://registry.{{.ts_suffix}}:443/{{.image_name}}:latest
  #############################################################################
  # machinecfg
  #
  create-machinecfg-oci:
    desc: Create the machinecfg OCI image
    vars:
      image_build_commands: nix-build /var/build/machinecfg.nix ; cat result > /var/build/machinecfg.tar.gz
      image_name: machinecfg
    cmds:
      - mkdir -p dist
      - incus file push machinecfg.nix forge/root/
      - incus exec forge -- apt install -y skopeo
      - incus exec forge -- docker pull nixos/nix
      - incus exec forge -- docker run --privileged --volume /root:/var/build nixos/nix bash -c "{{.image_build_commands}}"
      - incus file pull forge/root/machinecfg.tar.gz dist/
    generates:
      - dist/{{.image_name}}.tar.gz
    status:
      - test -f dist/{{.image_name}}.tar.gz
    sources:
      - "{{.image_name}}.nix"
  push-machinecfg-oci:
    desc: Push machinecfg OCI to the registry
    preconditions:
      - test -f dist/{{.image_name}}.tar.gz
    vars:
      image_name: machinecfg
    cmds:
      - skopeo copy {{.skopeo_opts}} docker-archive:dist/{{.image_name}}.tar.gz docker://registry.{{.ts_suffix}}:443/{{.image_name}}:latest
  #############################################################################
  # debootstrap
  #
  create-debootstrap-oci:
    desc: Create debootstrap OCI image
    vars:
      image_build_commands: nix-build /var/build/debootstrap.nix && cat result > /var/build/debootstrap.tar.gz
      image_name: debootstrap
    cmds:
      - mkdir -p dist
      - incus file push {{.image_name}}.nix forge/root/
      - incus exec forge -- apt install -y skopeo
      - incus exec forge -- docker pull nixos/nix
      - incus exec forge -- docker run --privileged --volume /root:/var/build nixos/nix bash -c "{{.image_build_commands}}"
      - incus file pull forge/root/{{.image_name}}.tar.gz dist/
    generates:
      - dist/{{.image_name}}.tar.gz
    status:
      - test -f dist/{{.image_name}}.tar.gz
  push-debootstrap-oci:
    desc: Push debootstrap OCI to the registry
    preconditions:
      - test -f dist/{{.image_name}}.tar.gz
    vars:
      image_name: debootstrap
    cmds:
      - skopeo copy {{.skopeo_opts}} docker-archive:dist/{{.image_name}}.tar.gz docker://registry.{{.ts_suffix}}:443/{{.image_name}}:latest
