version: 3
vars:
  skopeo_opts: --dest-tls-verify=false --override-arch=amd64 --override-os=linux
  ts_suffix:
    sh: tailscale dns status | awk '/suffix =/ {gsub(")","");print $NF}'
tasks:
  #############################################################################
  # flatcar-install
  # 
  create-flatcar-install-oci:
    desc: Create the flatcar-install tinkerbell action OCI image
    vars:
      image_build_commands: nix-build /var/build/flatcar-install.nix ; cat result > /var/build/flatcar-install.tar.gz
      image_name: flatcar-install
    cmds:
      - mkdir -p dist
      - incus file push flatcar-install.nix forge/root/
      - incus exec forge -- apt install -y skopeo
      - incus exec forge -- docker pull nixos/nix
      - incus exec forge -- docker run --privileged --volume /root:/var/build nixos/nix bash -c "{{.image_build_commands}}"
      - incus file pull forge/root/flatcar-install.tar.gz dist/
    generates:
      - dist/{{.image_name}}.tar.gz
    status:
      - test -f dist/{{.image_name}}.tar.gz
    sources:
      - "{{.image_name}}.nix"
  push-flatcar-install-oci:
    desc: Push flatcar-install OCI to the registry
    vars:
      image_name: flatcar-install
    sources:
      - dist/{{.image_name}}.tar.gz
      - "{{.image_name}}.nix"
    cmds:
      - skopeo copy {{.skopeo_opts}} docker-archive:dist/{{.image_name}}.tar.gz docker://registry.{{.ts_suffix}}:443/{{.image_name}}:latest
  #############################################################################
  # cloud-init
  # 
  create-cloud-init-oci:
    desc: Create the cloud-init OCI image
    vars:
      image_build_commands: nix-build /var/build/cloud-init.nix ; cat result > /var/build/cloud-init.tar.gz
      image_name: cloud-init
    cmds:
      - mkdir -p dist
      - incus file push cloud-init.nix forge/root/
      - incus exec forge -- apt install -y skopeo
      - incus exec forge -- docker pull nixos/nix
      - incus exec forge -- docker run --privileged --volume /root:/var/build nixos/nix bash -c "{{.image_build_commands}}"
      - incus file pull forge/root/cloud-init.tar.gz dist/
    generates:
      - dist/{{.image_name}}
    status:
      - test -f dist/{{.image_name}}.tar.gz
    sources:
      - "{{.image_name}}.nix"
  push-cloud-init-oci:
    desc: Push cloud-init OCI to the registry
    vars:
      image_name: cloud-init
    sources:
      - dist/{{.image_name}}.tar.gz
    cmds:
      - skopeo copy {{.skopeo_opts}} docker-archive:dist/{{.image_name}}.tar.gz docker://registry.{{.ts_suffix}}:443/{{.image_name}}:latest
